<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HPS Elektronik Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #dc2626;
            padding-bottom: 20px;
        }

        .header h1 {
            color: #dc2626;
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }

        .filters {
            margin-bottom: 20px;
            background-color: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
        }

        .filters h3 {
            margin: 0 0 10px 0;
            color: #333;
            font-size: 14px;
        }

        .filter-row {
            display: flex;
            margin-bottom: 5px;
        }

        .filter-label {
            font-weight: bold;
            width: 120px;
        }

        .filter-value {
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #dc2626;
            color: white;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .status-active {
            color: #16a34a;
            font-weight: bold;
        }

        .status-inactive {
            color: #dc2626;
            font-weight: bold;
        }

        .price {
            text-align: right;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>HPS Elektronik Export</h1>
        <p>Generated on: {{ $exportDate }}</p>
    </div>

    @if(!empty($filters) || !empty($search))
    <div class="filters">
        <h3>Applied Filters:</h3>
        @if(!empty($search))
        <div class="filter-row">
            <span class="filter-label">Search:</span>
            <span class="filter-value">{{ $search }}</span>
        </div>
        @endif
        @foreach($filters as $key => $value)
        @if(!empty($value))
        <div class="filter-row">
            <span class="filter-label">{{ ucfirst(str_replace('_', ' ', $key)) }}:</span>
            <span class="filter-value">{{ is_array($value) ? implode(', ', $value) : $value }}</span>
        </div>
        @endif
        @endforeach
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Wilayah</th>
                <th>Jenis Barang</th>
                <th>Merek</th>
                <th>Barang</th>
                <th>Tahun</th>
                <th>Harga (Rp)</th>
                <th>Status</th>
                <th>Grade</th>
                <th>Kondisi</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($hpsElektronik as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->kdwilayah }}</td>
                <td>{{ $item->jenis_barang }}</td>
                <td>{{ $item->merek }}</td>
                <td>{{ $item->barang }}</td>
                <td>{{ $item->tahun }}</td>
                <td class="price">{{ number_format($item->harga, 0, ',', '.') }}</td>
                <td>
                    <span class="{{ $item->active ? 'status-active' : 'status-inactive' }}">
                        {{ $item->active ? 'Aktif' : 'Tidak Aktif' }}
                    </span>
                </td>
                <td>{{ $item->grade }}</td>
                <td>{{ $item->kondisi }}</td>
                <td>{{ $item->created_at->format('Y-m-d H:i:s') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="11" style="text-align: center; padding: 20px; color: #666;">
                    No data found
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Total Records: {{ $hpsElektronik->count() }}</p>
        <p>Generated by HPS Dashboard System</p>
    </div>
</body>
</html>
